<?if(!defined("B_PROLOG_INCLUDED") || B_PROLOG_INCLUDED!==true)die();?>
<?
$aMenuLinks = Array(
    Array(
        "Поддержка",
        "#",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Сервисные центры",
        "#",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Драйверы",
        "#",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Вопрос-ответ",
        "#",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Гарантия",
        "#",
        Array(),
        Array(),
        ""
    )
);
?>
